# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Mukul Agarwal
tagline:          'Portfolio'
description:      ''

author:
  name:           'Mukul Agarwal'
  url:            http://agarwalmukul.github.io

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/agarwalmukul/agarwalmukul.github.io
